### ISSUE TITLE
Option for the play action to insert in current terminal

### ISSUE THREAD

**Issue by maxwellhibbert** [deepakg202/vscode-save-commands#10]
Thanks for a handy extension.

It would be sweet if there was an option to simply insert the command into the active terminal, rather than create a new one each time.

**Comment by deepakg202** [comment]
Sorry for the late reply. 
This was actually how it was working previously in the initial versions of the extension (0.0.2). It used to just copy the command and paste it in the active terminal. 
I will surely bring the feature back when i get time.
