### ISSUE TITLE
Can't Escape "{" characters in command

### ISSUE THREAD

**Issue by xantrk** [deepakg202/vscode-save-commands#13]
I have some docker commands I would like to save and they contain curly braces. But save-commands recognize them as placeholders. Is there a way to "escape" them to prevent this behaviour? Essentially I pass a json dictionary somewhere in the command as '{key:value}'.

Thank you for this awesome extension!

**Comment by deepakg202** [comment]
@xantrk Thanks for pointing it out. Will fix this soon.

**Comment by deepakg202** [comment]
Added an option in #14 to change the capturing group for the regex used. You can change between different `placeholderTypes` in settings so that it does not conflict with the json dictionary
