### ISSUE TITLE
Import/Export Issue with JSON Structure

### ISSUE THREAD

**Issue by Ranamzes** [deepakg202/vscode-save-commands#22]
### Description
When importing/exporting commands, there is an inconsistency in the JSON structure that prevents commands from being properly organized in folders.

### Current Behavior
1. When exporting commands, the JSON has this structure:
```json
{
  "global": {
    "commands": [
      {
        "id": "command-id",
        "name": "Command Name",
        "command": "command string",
        "placeholderTypeId": "singleCurlyBraces",
        "sortOrder": 0,
        "parentFolderId": "folder-id"
      }
    ],
    "folders": [...]
  }
}
```

2. But when importing, it expects:
```json
{
  "save-commands": {
    "global": {
      "commands": [...],
      "folders": [...]
    }
  }
}
```

### Expected Behavior
The export function should include the `save-commands` root object to match the import requirements.

### Steps to Reproduce
1. Create some commands in folders
2. Export commands to JSON
3. Try to import the same JSON file
4. Commands appear but not in their original folders

### Environment
- VS Code Version: latest
- Extension Version: latest
- OS: all platforms

### Suggested Fix
1. Update the export function to include the `save-commands` root object
2. Or update import function to handle both formats
3. Add documentation about required JSON structure

### Additional Context
This inconsistency makes it difficult to backup and restore commands with their folder structure intact. Currently, users need to manually modify the JSON structure between export and import.

**Comment by deepakg202** [comment]
Hi @Ranamzes,
I was unable to replicate the issue. import/export works fine for me. Testing it on VSCodium 1.94.2, MacOS. 
Ideally it should just reject the 2nd json format without any message. Is there anything else different going on here ?
If possible could you share a video to replicate this issue ?

**Comment by Ranamzes** [comment]
Hi @deepakg202,
Thanks for the quick response.
I tried again, but this time it worked without save-commands{...}. Something must have prevented it from working properly that time. I apologize for the inconvenience.

**Comment by deepakg202** [comment]
no worries. 
Closing this issue for now.
